FROM alpine:latest

ARG PB_VERSION=0.40.3
ARG TARGETARCH=amd64

WORKDIR /pb

ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_${TARGETARCH}.zip /tmp/pb.zip

RUN unzip /tmp/pb.zip -d /pb/ && \
    rm /tmp/pb.zip && \
    chmod +x /pb/pocketbase

COPY pocketbase/pb_migrations /pb/pb_migrations
COPY pocketbase/entrypoint.sh /pb/entrypoint.sh
RUN chmod +x /pb/entrypoint.sh

EXPOSE 8090

VOLUME ["/pb/pb_data"]

ENTRYPOINT ["/pb/entrypoint.sh"]
